export const FETCH_SEIHEKI = "FETCH_SEIHEKI";
export const FETCH_SEIHEKI_FULFILLED = "FETCH_SEIHEKI_FULFILLED";

export const FETCH_THEME = "FETCH_THEME";
export const FETCH_THEME_PENDING = "FETCH_THEME_PENDING";
export const FETCH_THEME_FULFILLED = "FETCH_THEME_FULFILLED"
export const FETCH_THEME_REJECTED = "FETCH_THEME_REJECTED"

export const FETCH_HISTORY = "FETCH_HISTORY";
export const FETCH_HISTORY_PENDING = "FETCH_HISTORY_PENDING";
export const FETCH_HISTORY_FULFILLED = "FETCH_HISTORY_FULFILLED";
export const FETCH_HISTORY_REJECTED = "FETCH_HISTORY_REJECTED";

export const FETCH_SEIHEKIS = "FETCH_SEIHEKIS";
export const FETCH_SEIHEKIS_PENDING = "FETCH_SEIHEKIS_PENDING";
export const FETCH_SEIHEKIS_FULFILLED = "FETCH_SEIHEKIS_FULFILLED";
export const FETCH_SEIHEKIS_REJECTED = "FETCH_SEIHEKIS_REJECTED";

export const PUT_AUTHOR = "PUT_AUTHOR";
